### ISSUE TITLE
Could not login into ChatGPT via Google

### ISSUE THREAD

**Issue by BernardIgiri** [flathub/io.github.anirbandey1.ChatbotClient#1]
When attempting to sign into ChatGPT via Google, I received the following message:

Couldn’t sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

**Comment by soufrabi** [comment]
Google authentication does not work properly in electron. This would require a fair bit of work.Email authentication works properly as of now.

**Comment by BernardIgiri** [comment]
When I use [nativefier](https://github.com/nativefier/nativefier) to create a ChatGPT desktop application, I use the Mozilla Firefox user agent as a work around. This is what I run in the terminal for nativefier:
```
nativefier --user-agent "Mozilla/5.0 (Windows NT 10.0; rv:74.0) Gecko/20100101" https://chat.openai.com/
```

**Comment by soufrabi** [comment]
Adding user-agent should fix the issue. Thanks for pointing it out. 😄

**Comment by soufrabi** [comment]
I have made the suggested change. The flatpak has been updated. Could you please verify if the problem is persisting.

**Comment by BernardIgiri** [comment]
It works now. Thank you!
